name: one_health_doctor_and_admin
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  app_boot: ^0.3.0
  charts_flutter: ^0.12.0
  cupertino_icons: ^1.0.2
  data_table_2: ^2.2.3
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_awesome_select: ^6.3.0
  get: ^4.6.5
  google_fonts: ^3.0.1
  image_picker: ^0.8.5+3
  image_picker_web: ^2.1.1
  pin_code_fields: ^7.4.0
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
