  List<String> medicinesList = [
    "Aciclovir(Zovirax)",
"Acrivastine",
"Adalimumab",
"Alendronic acid",
"Allopurinol",
"Alogliptin",
"Amitriptyline for depression",
"Amitriptyline for pain and migraine",
"Amlodipine",
"Amoxicillin",
"Anastrozole",
"Apixaban",
"Aspirin for pain relief",
"Aspirin-low-dose,see Low-dose aspirin",
"Atenolol",
"Atorvastatin",
"Azathioprine",
"Azithromycin",
"Baclofen",
"Beclometasone inhalers",
"Beclometasone nasal spray",
"Beclometasone skin creams",
"Bendroflumethiazide",
"Benzoyl peroxide",
"Benzydamine",
"Betahistine",
"Betamethasone for eyes,ears and nose",
"Betamethasone for skin",
"Betamethasone tablets",
"Bimatoprost",
"Bisacodyl",
"Bisoprolol",
"Brinzolamide",
"Budesonide inhalers",
"Budesonide nasal spray",
"Budesonide rectal foam and enemas",
"Budesonide tablets,capsules and granules",
"Bumetanide",
"Buprenorphine for pain",
"Buscopan(hyoscine butylbromide)",
"Calcipotriol",
"Candesartan",
"Carbamazepine",
"Carbimazole",
"Carbocisteine",
"Carmellose sodium",
"Carvedilol",
"Cefalexin",
"Cetirizine",
"Champix(varenicline)",
"Chloramphenicol",
"Chlorhexidine",
"Chlorphenamine(Piriton)",
"Cinnarizine",
"Ciprofloxacin",
"Citalopram",
"Clarithromycin",
"Clobetasol",
"Clobetasone",
"Clonazepam",
"Clopidogrel",
"Clotrimazole",
"Clotrimazole for thrush(Canesten)",
"Co-amoxiclav",
"Co-beneldopa",
"Co-careldopa",
"Co-codamol for adults",
"Co-codamol for children",
"Co-codaprin(aspirin and codeine)",
"Co-dydramol",
"Codeine",
"Colchicine",
"Cyanocobalamin",
"Cyclizine",
"Dabigatran",
"Dapagliflozin",
"Dexamethasone tablets and liquid",
"Diazepam",
"Diclofenac",
"Digoxin",
"Dihydrocodeine",
"Diltiazem",
"Diphenhydramine",
"Dipyridamole",
"Docusate",
"Domperidone",
"Donepezil",
"Dosulepin",
"Doxazosin",
"Doxycycline",
"Duloxetine",
"Edoxaban",
"Empagliflozin",
"Enalapril",
"Eplerenone",
"Erythromycin",
"Escitalopram",
"Esomeprazole",
"Ezetimibe",
"Felodipine",
"Fentanyl",
"Ferrous fumarate",
"Ferrous sulfate",
"Fexofenadine",
"Finasteride",
"Flucloxacillin",
"Fluconazole",
"Fluoxetine (Prozac)",
"Fluticasone inhalers",
"Fluticasone nasal spray and drops",
"Fluticasone skin creams",
"Folic acid",
"Furosemide",
"Fusidic acid",
"Fybogel (ispaghula husk)",
"Gabapentin",
"Gaviscon (alginic acid)",
"Gliclazide",
"Glimepiride",
"Glyceryl trinitrate (GTN)",
"Heparinoid",
"Hydrocortisone",
"Hydrocortisone buccal tablets",
"Hydrocortisone for piles and itchy bottom",
"Hydrocortisone for skin",
"Hydrocortisone injections",
"Hydrocortisone rectal foam",
"Hydrocortisone tablets",
"Hydroxocobalamin",
"Hydroxychloroquine",
"Hyoscine hydrobromide (Kwells and Joy-Rides)",
"Ibuprofen and codeine",
"Ibuprofen for adults (Nurofen)",
"Ibuprofen for children",
"Indapamide",
"Irbesartan",
"Isosorbide mononitrate and isosorbide dinitrate",
"Isotretinoin capsules (Roaccutane)",
"Isotretinoin gel (Isotrex)",
"Ketoconazole",
"Labetalol",
"Lactulose",
"Lamotrigine",
"Lansoprazole",
"Latanoprost",
"Lercanidipine",
"Letrozole",
"Levetiracetam",
"Levothyroxine",
"Lidocaine for mouth and throat",
"Lidocaine for piles and itchy bottom",
"Lidocaine skin cream",
"Linagliptin",
"Lisinopril",
"Lithium",
"Loperamide",
"Loratadine (Clarityn)",
"Lorazepam",
"Losartan",
"Low-dose aspirin",
"Lymecycline",
"Macrogol",
"Mebendazole",
"Mebeverine",
"Melatonin",
"Mesalazine",
"Metformin",
"Methadone",
"Methotrexate",
"Methylphenidate for adults",
"Methylphenidate for children",
"Metoclopramide",
"Metoprolol",
"Metronidazole",
"Mirabegron",
"Mirtazapine",
"Molnupiravir (Lagevrio)",
"Mometasone for skin",
"Mometasone inhalers",
"Mometasone nasal spray",
"Montelukast",
"Morphine",
"Naproxen",
"Nefopam",
"Nicorandil",
"Nifedipine",
"Nitrofurantoin",
"Nortriptyline",
"Nystatin",
"Olanzapine",
"Olmesartan",
"Omeprazole",
"Oxybutynin",
"Oxycodone",
"Pantoprazole",
"Paracetamol for adults",
"Paracetamol for children (Calpol)",
"Paroxetine",
"Paxlovid",
"Peppermint oil",
"Pepto-Bismol",
"Perindopril",
"Phenoxymethylpenicillin",
"Phenytoin",
"Pioglitazone",
"Pravastatin",
"Prednisolone tablets and liquid",
"Pregabalin",
"Prochlorperazine",
"Promethazine (Phenergan)",
"Propranolol",
"Pseudoephedrine (including Sudafed)",
"Quetiapine",
"Rabeprazole",
"Ramipril",
"Ranitidine",
"Remdesivir (Veklury)",
"Risedronate",
"Risperidone",
"Rivaroxaban",
"Ropinirole",
"Rosuvastatin",
"Salbutamol inhaler",
"Saxagliptin",
"Senna",
"Sertraline",
"Sildenafil (Viagra)",
"Simeticone",
"Simvastatin",
"Sitagliptin",
"Sodium valproate",
"Solifenacin",
"Sotalol",
"Sotrovimab (Xevudy)",
"Spironolactone",
"Sulfasalazine",
"Sumatriptan",
"Tadalafil",
"Tamsulosin",
"Temazepam",
"Terbinafine",
"Thiamine (vitamin B1)",
"Ticagrelor",
"Tolterodine",
"Topiramate",
"Tramadol",
"Tranexamic acid",
"Trazodone",
"Trimethoprim",
"Valproic acid",
"Valsartan",
"Varenicline, see Champix (varenicline)",
"Venlafaxine",
"Verapamil",
"Warfarin",
"Zolpidem",
"Zopiclone",
  ];